# Generated by Django 3.0 on 2020-02-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Féculents', 'Féculents'), ('Fruits/Légumes', 'Fruits/Légumes'), ('Conserves/Plats cuisinés', 'Conserves/Plats cuisinés'), ('Produits laitiers', 'Produits laitiers'), ('Desserts/Pain', 'Desserts/Pain'), ('Viandes/Oeufs', 'Viandes/Oeufs'), ('Boissons', 'Boissons'), ("Produits d'hygiène", "Produits d'hygiène"), ("Produits d'entretien", "Produits d'entretien"), ('Autres', 'Autres')], default='Gif', max_length=50),
        ),
    ]
