# Generated by Django 3.0.7 on 2020-06-10 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(help_text='Unique identifier required', max_length=254, unique=True, verbose_name='Email address')),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='Date of creation provided by default', verbose_name='Date joined')),
                ('is_active', models.BooleanField(default=True, help_text='Set to True by default', verbose_name='Is active')),
                ('is_staff', models.BooleanField(default=False, help_text='Set to False by default', verbose_name='Is staff')),
                ('is_superuser', models.BooleanField(default=False, help_text='Set to False by default', verbose_name='Is superuser')),
                ('first_name', models.CharField(help_text='Not empty', max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(help_text='Not empty', max_length=50, verbose_name='Last name')),
                ('profile_picture', models.ImageField(default='media/user/android.png', help_text="Set to 'media/user/android.png' by default", upload_to='media/user/', verbose_name='Profile picture url')),
                ('room_number', models.CharField(help_text='Null for staff members but required for simple users', max_length=50, null=True, verbose_name='Room number')),
                ('campus', models.CharField(choices=[('Gif', 'Gif'), ('Rennes', 'Rennes'), ('Metz', 'Metz')], help_text="Null for staff members but required for simple users : ['Gif','Metz','Rennes']", max_length=10, null=True, verbose_name='Campus')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Not empty', max_length=50, verbose_name='Name')),
                ('category', models.CharField(choices=[('Féculents', 'Féculents'), ('Fruits/Légumes', 'Fruits/Légumes'), ('Conserves/Plats cuisinés', 'Conserves/Plats cuisinés'), ('Produits laitiers', 'Produits laitiers'), ('Desserts/Pain', 'Desserts/Pain'), ('Viandes/Oeufs', 'Viandes/Oeufs'), ("Produits d'hygiène", "Produits d'hygiène"), ("Produits d'entretien", "Produits d'entretien"), ('Autres', 'Autres')], help_text="Must be in this list : ['Féculents','Fruits/Légumes','Viandes/Oeufs','Desserts/Pain','Conserves/Plats cuisinés','Produits laitiers',            'Produits d'entretien','Produits d'hygiène','Autres']", max_length=50, verbose_name='Category')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Collected', 'Collected'), ('Delivered', 'Delivered')], default='Available', help_text="Must be in this list : ['Available','Collected','Delivered'] Set to Available by default", max_length=50, verbose_name='Status')),
                ('product_picture', models.ImageField(default='media/product/apple.jpg', help_text="Set to 'media/product/apple.png' by default", upload_to='media/product/', verbose_name='Product picture url')),
                ('quantity', models.CharField(help_text='Not empty', max_length=50, verbose_name='Quantity')),
                ('expiration_date', models.DateField(help_text='Date format is: YYYY-MM-DD.', verbose_name='Expiration date')),
                ('campus', models.CharField(choices=[('Gif', 'Gif'), ('Rennes', 'Rennes'), ('Metz', 'Metz')], help_text="Must be in this list : ['Gif','Metz','Rennes']", max_length=10, verbose_name='Product location')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date of creation provided by default', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date of update provided by default', verbose_name='Updated at')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date of creation provided by default', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date of update provided by default', verbose_name='Updated at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
        ),
    ]
