# Generated by Django 3.0 on 2019-12-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='test',
        ),
        migrations.RemoveField(
            model_name='product',
            name='test',
        ),
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
    ]
