# Generated by Django 3.0 on 2019-12-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='description',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
