# Generated by Django 3.0 on 2019-12-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_uploadimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='boolean',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
