# Generated by Django 3.0 on 2020-01-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200120_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='user',
            name='campus',
            field=models.CharField(choices=[('G', 'Gif'), ('R', 'Rennes'), ('M', 'Metz')], max_length=1),
        ),
    ]
