# Generated by Django 3.0 on 2020-01-10 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200110_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='room',
            new_name='room_number',
        ),
    ]
