# Generated by Django 3.0.2 on 2020-02-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('api', '0003_auto_20200125_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Féculents', 'Féculents'), ('Fruits/Légumes', 'Fruits/Légumes'), ('Conserves/Plats cuisinés', 'Conserves/Plats cuisinés'), ('Produits laitiers', 'Produits laitiers'), ('Desserts/Pain', 'Desserts/Pain'), ('Viandes/Oeufs', 'Viandes/Oeufs'), ("Produits d'hygiène", "Produits d'hygiène"), ("Produits d'entretien", "Produits d'entretien"), ('Autres', 'Autres')], max_length=50),
        ),
    ]
