# Generated by Django 3.0 on 2019-12-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_uploadimage_boolean'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='integer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
