# Generated by Django 3.0 on 2019-12-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_uploadimage_integer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
