# Generated by Django 3.0 on 2019-12-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191213_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(default='/media/product/apple.jpg/', upload_to='media/product/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='/media/user/android.png', upload_to='media/user/'),
        ),
    ]
