# Generated by Django 3.0 on 2019-12-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191213_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(default='product/apple.jpg', upload_to='product/'),
        ),
    ]
