# Generated by Django 3.0 on 2019-12-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20191213_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='user/android.png', upload_to='rest/media/user/'),
        ),
    ]
