# Generated by Django 3.0 on 2019-12-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20191213_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(default='product/apple.jpg', upload_to='rest/media/product/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='media/user/android.png', upload_to='rest/media/user/'),
        ),
    ]
