# Generated by Django 3.0 on 2019-12-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20191213_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(default='rest/prout/product/apple.jpg', upload_to='rest/media/product/'),
        ),
    ]
