# Generated by Django 3.0 on 2019-12-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20191216_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='offerer',
            new_name='supplier',
        ),
    ]
