# Generated by Django 3.0 on 2019-12-17 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20191216_0934'),
        ('api', '0022_auto_20191216_1523'),
    ]

    operations = [
    ]
