# Generated by Django 3.0 on 2019-12-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_product_product_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_picture',
        ),
    ]
